version: '3.8'

services:

  web:
    build: ./project
    command: ./entrypoint.sh
    volumes:
      - ./project:/usr/src/app
    ports:
      - 8004:8000
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/foo
      - REDIS_URL=redis://redis
    depends_on:
      - db
    networks:
      - app_net

  db:
    image: postgres:15.3
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=foo
    volumes:
      - postgresql_data:/data
    networks:
      - app_net

  redis:
    image: redis:7-alpine
    networks:
      - app_net

networks:
  app_net:
    driver: bridge

volumes:
  postgresql_data:
    name: app-postgresql-data
